//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewEmployeeDetail
    {
        public int EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public int RecordStatusID { get; set; }
        public string RecordStatusName { get; set; }
    }
}
